/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutMe {
  'bio' : string,
  'isVisible' : boolean,
  'profilePhotoBlobId' : [] | [string],
}
export type Category = { 'categoryLongVideos' : null } |
  { 'categoryShorts' : null } |
  { 'categoryClientWork' : null };
export interface ContactFormSubmission {
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface ContactInfo {
  'instagram' : string,
  'email' : string,
  'phone' : string,
}
export interface NewVideoInput {
  'title' : string,
  'sortOrder' : bigint,
  'description' : string,
  'category' : Category,
  'youtubeUrl' : string,
}
export interface Photo {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'blobId' : string,
  'category' : string,
}
export interface ResultItem {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'blobId' : string,
  'category' : string,
}
export interface SiteText {
  'stat1Label' : string,
  'galleryDescription' : string,
  'aboutHeading' : string,
  'heroDescription' : string,
  'workLabel' : string,
  'navAbout' : string,
  'stat2Value' : string,
  'heroCta1' : string,
  'heroCta2' : string,
  'workHeading' : string,
  'heroScroll' : string,
  'heroName' : string,
  'heroBadge' : string,
  'heroSubtitle' : string,
  'contactGetInTouch' : string,
  'workDescription' : string,
  'stat2Label' : string,
  'contactSendMessage' : string,
  'stat3Value' : string,
  'contactLabel' : string,
  'contactHeading' : string,
  'navHome' : string,
  'contactDescription' : string,
  'aboutLabel' : string,
  'navBrand' : string,
  'navContact' : string,
  'navWork' : string,
  'stat1Value' : string,
  'galleryLabel' : string,
  'stat3Label' : string,
  'galleryHeading' : string,
  'footerName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'sortOrder' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'youtubeId' : string,
  'category' : Category,
  'youtubeUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPhoto' : ActorMethod<[string, string, string], undefined>,
  'addResult' : ActorMethod<[string, string, string], undefined>,
  'addVideo' : ActorMethod<[NewVideoInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactFormSubmission' : ActorMethod<[bigint], undefined>,
  'deletePhoto' : ActorMethod<[bigint], undefined>,
  'deleteResult' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'getAboutMe' : ActorMethod<[], AboutMe>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getContactInfo' : ActorMethod<[], ContactInfo>,
  'getPhoto' : ActorMethod<[bigint], Photo>,
  'getPhotoCategories' : ActorMethod<[], Array<string>>,
  'getPhotos' : ActorMethod<[], Array<Photo>>,
  'getResults' : ActorMethod<[], Array<ResultItem>>,
  'getSiteText' : ActorMethod<[], SiteText>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideo' : ActorMethod<[bigint], Video>,
  'getVideos' : ActorMethod<[], Array<Video>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateAboutMe' : ActorMethod<[string, [] | [string], boolean], undefined>,
  'updateContactInfo' : ActorMethod<[string, string, string], undefined>,
  'updatePhotoCategories' : ActorMethod<[Array<string>], undefined>,
  'updateSiteText' : ActorMethod<[SiteText], undefined>,
  'updateVideo' : ActorMethod<[bigint, NewVideoInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];