/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'categoryLongVideos' : IDL.Null,
  'categoryShorts' : IDL.Null,
  'categoryClientWork' : IDL.Null,
});
export const NewVideoInput = IDL.Record({
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'description' : IDL.Text,
  'category' : Category,
  'youtubeUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AboutMe = IDL.Record({
  'bio' : IDL.Text,
  'isVisible' : IDL.Bool,
  'profilePhotoBlobId' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactFormSubmission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const ContactInfo = IDL.Record({
  'instagram' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Photo = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'blobId' : IDL.Text,
  'category' : IDL.Text,
});
export const ResultItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'blobId' : IDL.Text,
  'category' : IDL.Text,
});
export const SiteText = IDL.Record({
  'stat1Label' : IDL.Text,
  'galleryDescription' : IDL.Text,
  'aboutHeading' : IDL.Text,
  'heroDescription' : IDL.Text,
  'workLabel' : IDL.Text,
  'navAbout' : IDL.Text,
  'stat2Value' : IDL.Text,
  'heroCta1' : IDL.Text,
  'heroCta2' : IDL.Text,
  'workHeading' : IDL.Text,
  'heroScroll' : IDL.Text,
  'heroName' : IDL.Text,
  'heroBadge' : IDL.Text,
  'heroSubtitle' : IDL.Text,
  'contactGetInTouch' : IDL.Text,
  'workDescription' : IDL.Text,
  'stat2Label' : IDL.Text,
  'contactSendMessage' : IDL.Text,
  'stat3Value' : IDL.Text,
  'contactLabel' : IDL.Text,
  'contactHeading' : IDL.Text,
  'navHome' : IDL.Text,
  'contactDescription' : IDL.Text,
  'aboutLabel' : IDL.Text,
  'navBrand' : IDL.Text,
  'navContact' : IDL.Text,
  'navWork' : IDL.Text,
  'stat1Value' : IDL.Text,
  'galleryLabel' : IDL.Text,
  'stat3Label' : IDL.Text,
  'galleryHeading' : IDL.Text,
  'footerName' : IDL.Text,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sortOrder' : IDL.Nat,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'youtubeId' : IDL.Text,
  'category' : Category,
  'youtubeUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addVideo' : IDL.Func([NewVideoInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactFormSubmission' : IDL.Func([IDL.Nat], [], []),
  'deletePhoto' : IDL.Func([IDL.Nat], [], []),
  'deleteResult' : IDL.Func([IDL.Nat], [], []),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'getAboutMe' : IDL.Func([], [AboutMe], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
  'getPhoto' : IDL.Func([IDL.Nat], [Photo], ['query']),
  'getPhotoCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
  'getResults' : IDL.Func([], [IDL.Vec(ResultItem)], ['query']),
  'getSiteText' : IDL.Func([], [SiteText], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideo' : IDL.Func([IDL.Nat], [Video], ['query']),
  'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAboutMe' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
  'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePhotoCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateSiteText' : IDL.Func([SiteText], [], []),
  'updateVideo' : IDL.Func([IDL.Nat, NewVideoInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'categoryLongVideos' : IDL.Null,
    'categoryShorts' : IDL.Null,
    'categoryClientWork' : IDL.Null,
  });
  const NewVideoInput = IDL.Record({
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'description' : IDL.Text,
    'category' : Category,
    'youtubeUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AboutMe = IDL.Record({
    'bio' : IDL.Text,
    'isVisible' : IDL.Bool,
    'profilePhotoBlobId' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactFormSubmission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const ContactInfo = IDL.Record({
    'instagram' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Photo = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'blobId' : IDL.Text,
    'category' : IDL.Text,
  });
  const ResultItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'blobId' : IDL.Text,
    'category' : IDL.Text,
  });
  const SiteText = IDL.Record({
    'stat1Label' : IDL.Text,
    'galleryDescription' : IDL.Text,
    'aboutHeading' : IDL.Text,
    'heroDescription' : IDL.Text,
    'workLabel' : IDL.Text,
    'navAbout' : IDL.Text,
    'stat2Value' : IDL.Text,
    'heroCta1' : IDL.Text,
    'heroCta2' : IDL.Text,
    'workHeading' : IDL.Text,
    'heroScroll' : IDL.Text,
    'heroName' : IDL.Text,
    'heroBadge' : IDL.Text,
    'heroSubtitle' : IDL.Text,
    'contactGetInTouch' : IDL.Text,
    'workDescription' : IDL.Text,
    'stat2Label' : IDL.Text,
    'contactSendMessage' : IDL.Text,
    'stat3Value' : IDL.Text,
    'contactLabel' : IDL.Text,
    'contactHeading' : IDL.Text,
    'navHome' : IDL.Text,
    'contactDescription' : IDL.Text,
    'aboutLabel' : IDL.Text,
    'navBrand' : IDL.Text,
    'navContact' : IDL.Text,
    'navWork' : IDL.Text,
    'stat1Value' : IDL.Text,
    'galleryLabel' : IDL.Text,
    'stat3Label' : IDL.Text,
    'galleryHeading' : IDL.Text,
    'footerName' : IDL.Text,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sortOrder' : IDL.Nat,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'youtubeId' : IDL.Text,
    'category' : Category,
    'youtubeUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addResult' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addVideo' : IDL.Func([NewVideoInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactFormSubmission' : IDL.Func([IDL.Nat], [], []),
    'deletePhoto' : IDL.Func([IDL.Nat], [], []),
    'deleteResult' : IDL.Func([IDL.Nat], [], []),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'getAboutMe' : IDL.Func([], [AboutMe], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getContactInfo' : IDL.Func([], [ContactInfo], ['query']),
    'getPhoto' : IDL.Func([IDL.Nat], [Photo], ['query']),
    'getPhotoCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPhotos' : IDL.Func([], [IDL.Vec(Photo)], ['query']),
    'getResults' : IDL.Func([], [IDL.Vec(ResultItem)], ['query']),
    'getSiteText' : IDL.Func([], [SiteText], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideo' : IDL.Func([IDL.Nat], [Video], ['query']),
    'getVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAboutMe' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text), IDL.Bool], [], []),
    'updateContactInfo' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePhotoCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateSiteText' : IDL.Func([SiteText], [], []),
    'updateVideo' : IDL.Func([IDL.Nat, NewVideoInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };